version: 2
updates:
    - package-ecosystem: "github-actions"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "GHA"
      labels:
          - "GHA"
          - "dependencies"
      open-pull-requests-limit: 1
      target-branch: "master"
      groups:
        gha-dependencies:
            patterns:
                - "workiva/gha-*"
                - "actions/*"
      directory: "/"
      pull-request-branch-name:
          separator: "/"
    - package-ecosystem: "pub"
      directory: "/"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 2
      labels:
          - "dependencies"
      ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]