name: dependency_validator
version: 2.0.1
description: Checks for missing, under-promoted, over-promoted, and unused dependencies.
homepage: https://github.com/Workiva/dependency_validator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  build_config:
    git:
      url: git@github.com:dart-lang/build.git
      path: build_config
      ref: master

dependencies:
  args: ^2.0.0
  build_config: ^0.4.2
  checked_yaml: ^2.0.1
  glob: ^2.0.1
  json_annotation: ^4.0.1
  logging: ^1.0.1
  package_config: ^2.0.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^4.1.0
  test: ^1.16.8
  test_descriptor: ^2.0.0
  workiva_analysis_options: ^1.2.0

executables:
  dependency_validator:

dependency_validator:
  ignore:
    - json_serializable
    - _foo
    - foo
    - _bar
    - bar
    - foo1
    - foo_foo
